#need to convert skip NAs to 0s

x <- paq %>% rename(
  vigorous_work = PAQ605,
  moderate_work = PAQ620,
  vigorous_rec = PAQ650,
  moderate_rec = PAQ665,
  walkorbike = PAQ635,
  vig_work_days = PAQ610,
  vig_work_min = PAD615,
  mod_work_days = PAQ625,
  mod_work_min = PAD630,
  vig_rec_days = PAQ655,
  vig_rec_min = PAD660,
  mod_rec_days = PAQ670,
  mod_rec_min = PAD675,
  wob_days = PAQ640,
  wob_min = PAD645
) %>%
  mutate(
    vigorous_work = ifelse(vigorous_work >= 7, NA, vigorous_work),
    vigorous_work = ifelse(vigorous_work == 1, 1, 0),
    moderate_work = ifelse(moderate_work >= 7, NA, moderate_work),
    moderate_work = ifelse(moderate_work == 1, 1, 0),
    vigorous_rec = ifelse(vigorous_rec >= 7, NA, vigorous_rec),
    vigorous_rec = ifelse(vigorous_rec == 1, 1, 0),
    moderate_rec = ifelse(moderate_rec >= 7, NA, moderate_rec),
    moderate_rec = ifelse(moderate_rec == 1, 1, 0),
    walkorbike = ifelse(walkorbike >= 7, NA, walkorbike),
    walkorbike = ifelse(walkorbike == 1, 1, 0),
    vig_work_days = ifelse(vig_work_days >= 77, NA, vig_work_days),
    vig_work_days = ifelse(vigorous_work == 0, 0, vig_work_days),
    vig_work_min = ifelse(vig_work_min >= 7777, NA, vig_work_min),
    vig_work_min = ifelse(vigorous_work == 0, 0, vig_work_min),
    mod_work_days = ifelse(mod_work_days >= 77, NA, mod_work_days),
    mod_work_days = ifelse(moderate_work == 0, 0, mod_work_days),
    mod_work_min = ifelse(mod_work_min >= 7777, NA, mod_work_min),
    mod_work_min = ifelse(moderate_work == 0, 0, mod_work_min),
    vig_rec_days = ifelse(vig_rec_days >= 77, NA, vig_rec_days),
    vig_rec_days = ifelse(vigorous_rec == 0, 0, vig_rec_days),
    vig_rec_min = ifelse(vig_rec_min >= 7777, NA, vig_rec_min),
    vig_rec_min = ifelse(vigorous_rec == 0, 0, vig_rec_min),
    mod_rec_days = ifelse(mod_rec_days >= 77, NA, mod_rec_days),
    mod_rec_days = ifelse(moderate_rec == 0, 0, mod_rec_days),
    mod_rec_min = ifelse(mod_rec_min >=7777, NA, mod_rec_min),
    mod_rec_min = ifelse(moderate_rec == 0, 0, mod_rec_min),
    wob_days = ifelse(wob_days >= 77, NA, wob_days),
    wob_days = ifelse(walkorbike == 0, 0, wob_days),
    wob_min = ifelse(wob_min >= 7777, NA, wob_min),
    wob_min = ifelse(walkorbike == 0, 0, wob_min),
    vig_work_MET = ((vig_work_days*vig_work_min)/60)*8,
    mod_work_MET = ((mod_work_days*mod_work_min)/60)*4,
    total_work_MET = vig_work_MET + mod_work_MET,
    vig_rec_MET = ((vig_rec_days*vig_rec_min)/60)*8,
    mod_rec_MET = ((mod_rec_days*mod_rec_min)/60)*4,
    total_rec_MET = vig_rec_MET + mod_rec_MET,
    wob_MET = ((wob_days*wob_min)/60)*4,
    tot_MET = total_work_MET + total_rec_MET + wob_MET, #MET from NHANES appendix 1
  )

# (
# vigorous_work = ifelse(vigorous_work >= 7, NA, vigorous_work),
# vigorous_work = ifelse(vigorous_work == 1, 1, 0),
# moderate_work = ifelse(moderate_work >= 7, NA, moderate_work),
# moderate_work = ifelse(moderate_work == 1, 1, 0),
# vigorous_rec = ifelse(vigorous_rec >= 7, NA, vigorous_rec),
# vigorous_rec = ifelse(vigorous_rec == 1, 1, 0),
# moderate_rec = ifelse(moderate_rec >= 7, NA, moderate_rec),
# moderate_rec = ifelse(moderate_rec == 1, 1, 0),
# walkorbike = ifelse(walkorbike >= 7, NA, walkorbike),
# walkorbike = ifelse(walkorbike == 1, 1, 0),
# vig_work_days = ifelse(vig_work_days >= 77, NA, vig_work_days),
# vig_work_min = ifelse(vig_work_min >= 7777, NA, vig_work_min),
# mod_work_days = ifelse(mod_work_days >= 77, NA, mod_work_days),
# mod_work_min = ifelse(mod_work_min >= 7777, NA, mod_work_min),
# vig_rec_days = ifelse(vig_rec_days >= 77, NA, vig_rec_days),
# vig_rec_min = ifelse(vig_rec_min >= 7777, NA, vig_rec_min),
# mod_rec_days = ifelse(mod_rec_days >= 77, NA, mod_rec_days),
# mod_rec_min = ifelse(mod_rec_min >=7777, NA, mod_rec_min),
# wob_days = ifelse(wob_days >= 77, NA, wob_days),
# wob_min = ifelse(wob_min >= 7777, NA, wob_min),
# vig_work_METhpw = ((vig_work_days*vig_work_min)/60)*8,
# activity_MET = vigorous_work*8 + moderate_work*4 + vigorous_rec*8 + moderate_rec*4 + walkorbike*4 #MET from NHANES appendix 1
# )
